#pragma once

/* Trackball */
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP18
#define SPI_MOSI_PIN GP19
#define SPI_MISO_PIN GP20
#define POINTING_DEVICE_CS_PIN GP21

#define ROTATIONAL_TRANSFORM_ANGLE -100
// #define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y

/* Reset */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
